name: Install Python package and pylint all

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Lint with pylint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pwd
        ls -lah
        find . \( \( -name env -o -name yolov5 \) -prune \) -o -type f -name "*.py" -print | xargs pylint --rcfile /home/runner/work/1.5-meter-monitor/1.5-meter-monitor/.pylintrc

